config/routes.rb
Rails.application.routes.draw do


 devise_for :users

 devise_scope :user do
   get '/users/sign_out' => 'devise/sessions#destroy'
 end

 resources :users

  resources :novels

 get 'search_novels', to: 'novels#search'

  root 'welcome#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)


    can :read, :all

    if user.present?
      can :manage, Novel, user_id: user.id
      if user.admin?
        can :manage, :all
      end
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/novel.rb
class Novel < ApplicationRecord
  belongs_to :user

  def self.search(param)
    param.strip!
    param.downcase!
    to_send_back = (name_matches(param)+description_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.name_matches(param)
    matches('name', param)
  end

  def self.description_matches(param)
    matches('description', param)
  end

  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :novels,dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

end

app/controllers/novels_controller.rb
class NovelsController < ApplicationController

  # before_action :authenticate_user!

  load_and_authorize_resource
  # http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  before_action :set_novel, only: [:edit, :update, :show, :destroy]
  # before_action :require_user, except: [:index, :show]
  # before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @novels = Novel.paginate(page: params[:page],per_page: 5)
  end

  def show

  end

  def new
    @novel = Novel.new
  end

  def edit
  end

  def create
    @novel = Novel.new(novel_params)
    @novel.user = current_user
    if @novel.save
      flash[:success] = 'novel was successfully created'
      redirect_to @novel
    else
      render 'new'
    end
  end

  def update
    if @novel.update(novel_params)
      flash[:success] = 'novel was successfully created'
      redirect_to @novel
    end
  end

  def destroy
    @novel.destroy
    flash[:danger] = "novel was successfully deleted"
    # respond_to do |format|
    #   format.html {redirect_to novels_url,notice: "deleted"}
    #   format.json {head :no_content}
    #   format.js
    # end

    redirect_to novels_path
  end



  def search
    if params[:novel].blank?
      flash.now[:danger] = "empty string"
    else
      @novels_search = Novel.search(params[:novel])
      flash.now[:danger] = "no user matches" if @novels_search .blank?
    end
    # render json: @novels_search
      respond_to do |format|
      format.js {render partial: 'novels/result'}
    end
  end



  private

  def set_novel
    @novel = Novel.find(params[:id])
  end


  def novel_params
    params.require(:novel).permit(:name, :publisher,:description,:image)
  end

  def require_same_user
    if current_user != @novel.user and !current_user.admin?
      flash[:danger] = "You can only edit or delete your own novel"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @users = User.paginate(page: params[:page],per_page: 5)
  end

  def show
    @user = User.find(params[:id])
    @user_novels = @user.novels.paginate(page: params[:page], per_page: 5)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book1s_helper.rb
module Book1sHelper
end

app/helpers/novel_helper.rb
module NovelHelper
end

app/helpers/novels_helper.rb
module NovelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Alpha", root_path, class: "navbar-brand" %>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "New Book", new_novel_path %></li>
        <% end %>

        <li><%= link_to "Novels", novels_path %></li>


        <li><%= link_to "Users", users_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to current_user.username, edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li> <%= link_to 'Login', new_user_session_path %></li>
          <li> <%= link_to 'Signup', new_user_registration_path %></li>
        <% end %>
      </ul>

    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Book" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

  <%= render 'layouts/navbar' %>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

      </div><!--/row-->

      <footer>
        <p>&copy; Company 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/novels/_form.html.erb
<%= render "shared/errors", obj: @novel %>

<div class= "row">
  <div class="col-md-12">
<%#= form_for  @novel, local: true do |form| %>
    <%= form_with(model:@novel ,local: true, :html => {class: "form-horizontal", role: "form"})  do |form| %>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= form.label :name %><br>
        </div>
        <div class="col-sm-10">
          <%= form.text_field :name ,class: "form-control", placeholder: "Name"%>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= form.label :publisher %><br>
        </div>
        <div class="col-sm-10">
          <%= form.text_field :publisher , rows:10 ,class: "form-control", placeholder: "Publisher"%>
        </div>
      </div>

       <div class="form-group">
              <div class="control-label col-sm-2">
                <%= form.label :description %><br>
              </div>
              <div class="col-sm-10">
                <%= form.text_area :description ,rows:10, class: "form-control", placeholder: "Description"%>
              </div>
            </div>


<!-- <div class="form-group">-->
<!--   <div class="control-label col-sm-2">-->
<!--   <%#= form.label :price %><br>-->
<!--           </div>-->
<!--           <div class="col-sm-10">-->
   <%#= form.text_field :price , class: "form-control", placeholder: "Price"%>
<!--           </div>-->
<!--         </div>-->

       <div class="form-group">
              <div class="control-label col-sm-2">
                <%= form.label :image %><br>
              </div>
              <div class="col-sm-10">
                <%= form.file_field :image , class: "form-control"%>
              </div>
            </div>


      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= form.submit  class: "btn btn-primary btn-lg" %>
        </div>
      </div>

      <div class=" col-xs-4 col-xs-offset-4">
        [ <%= link_to "Back", novels_path %> ]
      </div>


    <% end %>
  </div>
</div>

app/views/novels/_novel.html.erb
<% obj.each do |novel| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg " id="novel_<%= novel.id %>">
        <div class="article-title">
          <%= link_to novel.name, novel_path(novel) %>
        </div>
        <div class="article-body">
          <%= truncate(novel.description, lenght: 100) %>
          <div class="article-meta-details">
            <small>publisher: <%= novel.publisher %></small>
            <br>
            <small>Created by <%= novel.user ? novel.user.username : "no author " %>
              ,<%= time_ago_in_words(novel.created_at) %> ago,
              last update <%= time_ago_in_words(novel.updated_at) %>
            </small>
          </div>
        </div>
        <%# if novel.image.attached? %>
        <%#= link_to image_tag novel.image , size: "100x100"%>
        <%#end %>
        <%# if user_signed_in? && (current_user == novel.user || current_user.admin?) %>
        <div class="article-actions">
          <% if can? :update, novel %>
            <%= link_to "Edit", edit_novel_path(novel), class: "btn btn-xs btn-primary" %>
          <% end %>

          <% if can? :delete, novel %>
            <%= link_to "Delete", novel_path(novel), method: :delete, data: {confirm: "Are you sure ? "}, class: "btn btn-xs btn-danger", remote: true %>
          <% end %>

        </div>
<%# end %>
      </div>
    </div>
  </div>
<% end %>

app/views/novels/_result.html.erb
<% if params[:action] == 'search' %>
  <div class="results-block">
    <%= bootstrap_flash %>
  </div>
<% end %>

<%# if @novels_search %>
  <%# if @novels_search.size > 0 %>
<!--    <div id="friend-lookup-results" class="well results-block col-md-10">-->
<!--      <table class="search-results-table col-md-12">-->
<!--        <tbody>-->
        <%# @novels_search.each do |novel| %>
<!--          <tr>-->
<!--            <td><strong>Name:</strong> <%#= novel.name %></td>-->
<!--            <td><strong>Description:</strong> <%#= novel.description %></td>-->
<!--            <td><%#= link_to 'View novel', novel_path(novel), class: "btn btn-xs btn-primary" %></td>-->
<!--          </tr>-->

        <%# end %>
<!--        </tbody>-->
<!--      </table>-->
<!--    </div>-->
  <%# end %>
<%# end %>


<% if @novels_search %>
<% if @novels_search.size > 0 %>

<% @novels_search.each do |novel| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg " id="novel_<%= novel.id %>">
        <div class="article-title">
          <%= link_to novel.name, novel_path(novel) %>
        </div>
        <div class="article-body">
          <%= truncate(novel.description, lenght: 100) %>
          <div class="article-meta-details">
            <small>publisher: <%= novel.publisher %></small>
            <br>
            <small>Created by <%= novel.user ? novel.user.username : "no author " %>
              ,<%= time_ago_in_words(novel.created_at) %> ago,
              last update <%= time_ago_in_words(novel.updated_at) %>
            </small>
          </div>
        </div>
        <%# if novel.image.attached? %>
        <%#= link_to image_tag novel.image , size: "100x100"%>
        <%#end %>
        <%# if user_signed_in? && (current_user == novel.user || current_user.admin?) %>
        <div class="article-actions">
          <% if can? :update, novel %>
            <%= link_to "Edit", edit_novel_path(novel), class: "btn btn-xs btn-primary" %>
          <% end %>

          <% if can? :delete, novel %>
            <%= link_to "Delete", novel_path(novel), method: :delete, data: {confirm: "Are you sure ? "}, class: "btn btn-xs btn-danger", remote: true %>
          <% end %>

        </div>
<%# end %>
      </div>
    </div>
  </div>
<% end %>
<% end %>
<% end %>

app/views/novels/_result.js.erb
$('#results').html('<%= j ( render 'novels/result.html') %>')

$('#container_novel').hide();

app/views/novels/destroy.js.erb
$('#novel_<%= @novel.id %>').fadeOut(500,function () {
    console.log('abcdef');
    $(this).remove();
})

app/views/novels/edit.html.erb
<%= render 'novels/form' %>

app/views/novels/index.html.erb
<h1 align="center"> novels </h1>

<% if user_signed_in? %>
  <%= link_to "New novel", new_novel_path, class: "btn btn-md btn-primary" %>
<% end %>
<br>

<hr>

<% if params[:action] == 'search' %>
  <div class="results-block">
    <%= bootstrap_flash %>
  </div>
<% end %>

<div id="novel-lookup" align="center">
  <%= form_tag search_novels_path, remote: true, method: :get,

               id: "novel-lookup-form" do %>
    <div class="form-group row no-padding text-center col-md-12">
      <div class="col-md-10">
        <%= text_field_tag :novel, params[:novel],

                           placeholder: "Novel ticker symbol",
                           autofocus: true,
                           class: "form-control search-box input-lg" %>
      </div>
      <div class="col-md-2">
        <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
          <i class="fa fa-search"></i> Search
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="results">
  <%= render 'novels/result' %>
</div>



<div align="center ">
  <%= will_paginate %>
</div>

<div id="container_novel">
  <%= render 'novels/novel', obj: @novels %>
</div>

<div align="center ">
  <%= will_paginate %>
</div>

app/views/novels/new.html.erb
<%= render 'novels/form' %>

app/views/novels/show.html.erb
<h2 align="center">
  Name: <%= @novel.name %>
</h2>

<div class="well col-xs-8 col-xs-offset-2">
  <% if @novel.user %>
    <ul class="listing">
      <div class="row center">
        <div class="well col-md-4 col-md-offset-4">
          <li>Created by:</li>
<!--          <li><%#= link_to gravatar_for(@novel.user), user_path(@novel.user) %></li>-->
          <li class="article-title">
            <%= link_to @novel.user.username, user_registration_path(@novel.user) %>
          </li>
          <li>
            <small><%= pluralize(@novel.user.novels.count, "novel") if @novel.user.novels %></small>
          </li>
        </div>
      </div>
    </ul>
  <% end %>
  <h4 class="description"><strong>Description:</strong></h4>
  <hr>
  <%= @novel.description %>
  <h5>
    <strong>Publisher: </strong>
    <%= simple_format(@novel.publisher) %>
  </h5>
  <div>
    <h3>image:</h3>
    <%# if @novel.image.attached? %>
      <%#= link_to image_tag @novel.image , class: "thumbnail"%>
    <%#end %>
  </div>


  <div class="article-actions">
    <% if user_signed_in? && (current_user == @novel.user || current_user.admin?) %>
      <%= link_to "Edit", edit_novel_path(@novel), class: "btn btn-xs btn-primary" %>
      <%= link_to "Delete", novel_path, method: :delete, data: {confirm: "Are you sure ? "}, class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "View all novels", novels_path, class: "btn btn-xs btn-success" %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <div id="error_explanation">
            <h2>
              <%= pluralize(obj.errors.count, "error") %> prohibited
              this article from being saved:
            </h2>
          </div>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/users/index.html.erb
<h1 align="center"> Users </h1>


<div class="center">
  <%= will_paginate %>
</div>
<%# @articles.each do |article| %>


<% @users.each do |user| %>
  <ul class="listing">
    <div class="row">
      <div class="well col-md-4 col-md-offset-4 center">
<!--        <li><%#= link_to gravatar_for(user), user_path(user) %></li>-->
        <li class="article-title">
          <%= link_to user.username, user_path(user) %> <%= "(Admin)" if user.admin? %>
        </li>
        <li><small><%= pluralize(user.novels.count,"novels") if user.novels %></small></li>
        <% if user_signed_in? and current_user.admin? %>
          <li><%=link_to "edit", edit_user_path(user) %></li>

          <li><%=link_to "delete", user_path(user),method: :delete,data: {confirm: "Are u sure ? "} %></li>
        <% end %>
      </div>
    </div>
  </ul>



  <!--  <div class="row">-->
  <!--    <div class="col-xs-8 col-xs-offset-2">-->
  <!--      <div class="well well-lg">-->
  <!--        <div class="article-title">-->
  <%#= link_to user.username, user_path(user) %>
  <!--        </div>-->
  <!--        <div class="article-body">-->
  <%#= truncate(user.email) %>
  <!--        </div>-->
  <!--        <div class="article-actions">-->
  <%#= link_to "Edit", edit_user_path(user), class: "btn btn-xs btn-primary" %>
  <%#= link_to "Delete", user_path(user), method: :delete, data: {confirm: "Are you sure ? "}, class: "btn btn-xs btn-danger" %>
  <!--        </div>-->
  <!--      </div>-->
  <!--    </div>-->
  <!--  </div>-->
<% end %>
<div class="center">
  <%= will_paginate %>
</div>

app/views/users/show.html.erb
<h1 align="center"> Welcome to  <%= @user.username %> </h1>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%#= gravatar_for @user, size: 100 %>
  </div>
</div>





<h4 align="center"> <%= @user.username %> 's Items</h4>


<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#home">Novels</a></li>
  <li><a data-toggle="tab" href="#menu1">Articles</a></li>

</ul>
<hr>

<div class="tab-content">
<!--  <div id="home" class="tab-pane fade ">-->
<!--    <div class="center">-->
      <%#= will_paginate @user_articles %>
<!--    </div>-->
    <%#= render 'articles/article', obj: @user.articles %>

<!--    <div class="center">-->
      <%#= will_paginate @user_articles %>
<!--    </div>-->
<!--  </div>-->
  <div id="menu1" class="tab-pane fade in active">
    <div class="center">
      <%= will_paginate @user_novels %>
    </div>
    <%= render 'novels/novel', obj: @user.novels %>

    <div class="center">
      <%= will_paginate @user_novels %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<% if user_signed_in?  %>
  <h1 align="center"> Welcome <%= current_user.username %> </h1>
<% else  %>

  <div class="center">
    <h1 align="center"> Welcome Alpha </h1>
    <hr>

    <%= link_to 'login', new_user_session_path, class: "btn btn-lg btn-info"%>
    <%= link_to 'signup', new_user_registration_path, class: "btn btn-lg btn-success" %>
  </div>

<% end %>





<%#= link_to 'Logout', destroy_user_session_path %>